<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <DebugType>embedded</DebugType>

    <!-- 単一ファイル配布 (SingleFile) 関連の設定 -->
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <PublishReadyToRun>true</PublishReadyToRun>
    <!-- 自己解凍時にネイティブライブラリやコンテンツを含める設定 -->
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>

    <!-- アプリケーションのメタデータ -->
    <SatelliteResourceLanguages>_</SatelliteResourceLanguages>
    <Version>0.0.1</Version>
    <AssemblyVersion>0.0.1.0</AssemblyVersion>
    <FileVersion>0.0.1.0</FileVersion>
    <Company>TimeLeaf Project</Company>
    <Product>TimeLeaf</Product>
    <Description>プロジェクト管理ツール</Description>
    <Copyright>Copyright © 2026 Leaf Project</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.3" />
  </ItemGroup>

</Project>
